
-- GRDB Version 1.0.0

CREATE TABLE IF NOT EXISTS grdb_Upload_Validation_Changes (
iValidationID bigint NOT NULL AUTO_INCREMENT,
iUploadlogID bigint DEFAULT NULL,
cRateType enum('OFR','FOB','PLC') DEFAULT NULL,
cType enum('WO','WE') DEFAULT NULL,
cHeaderColumn varchar(20) DEFAULT NULL,
cInvalidValue varchar(30) DEFAULT NULL,
cValidValue varchar(20) DEFAULT NULL,
cOptionalColumn1 varchar(255) DEFAULT NULL,
cOptionalColumn2 varchar(255) DEFAULT NULL,
cOptionalColumn3 varchar(255) DEFAULT NULL,
iStatus int DEFAULT NULL,
iEnteredby int DEFAULT NULL,
tEntered datetime DEFAULT '0000-00-00 00:00:00',
iUpdatedby int DEFAULT NULL,
tUpdated datetime DEFAULT '0000-00-00 00:00:00',
PRIMARY KEY (iValidationID)
);


CREATE TABLE IF NOT EXISTS job (
id int NOT NULL AUTO_INCREMENT,
user_id varchar(255) NOT NULL,
status varchar(255) NOT NULL,
source varchar(255) NOT NULL,
file_path varchar(255) NOT NULL,
file_name varchar(225) DEFAULT NULL,
sheet_type varchar(255) DEFAULT NULL,
file_type varchar(45) DEFAULT NULL,
customer_name varchar(255) NOT NULL,
office_id varchar(255) NOT NULL,
created_at datetime DEFAULT CURRENT_TIMESTAMP,
last_updated_at datetime DEFAULT NULL ON UPDATE CURRENT_TIMESTAMP,
file_size bigint DEFAULT NULL,
total_row_num int DEFAULT NULL,
error_row_num int DEFAULT NULL,
error_log_filepath varchar(255) DEFAULT NULL,
correct_log_filepath varchar(255) DEFAULT NULL,
process_status varchar(45) DEFAULT NULL,
data_inserted enum('Y','N','E') DEFAULT 'N',
formatval_starttime datetime(6) DEFAULT NULL,
formatval_endtime datetime(6) DEFAULT NULL,
formatval_processtime time DEFAULT NULL,
rows_validated int DEFAULT NULL,
val_starttime datetime(6) DEFAULT NULL,
val_endtime datetime(6) DEFAULT NULL,
val_processtime time DEFAULT NULL,
insertion_starttime datetime(6) DEFAULT NULL,
insertion_endtime datetime(6) DEFAULT NULL,
insertion_processtime time DEFAULT NULL,
original_filename varchar(255) DEFAULT NULL,
exceptions varchar(500) DEFAULT NULL,
PRIMARY KEY (id)
);


CREATE TABLE IF NOT EXISTS auth_token (
id INT AUTO_INCREMENT PRIMARY KEY,
token VARCHAR(100),
creation_at DATETIME DEFAULT CURRENT_TIMESTAMP
);


CREATE TABLE IF NOT EXISTS user_auth_token(
id INT AUTO_INCREMENT PRIMARY KEY,
user_name VARCHAR(100),
auth_token_id INT,
email varchar(100) DEFAULT NULL,
FOREIGN KEY (auth_token_id) REFERENCES auth_token(id)
);


CREATE TABLE IF NOT EXISTS grdb_FreightOnBoard_Write (
iFreightOnBoardID bigint(20) NOT NULL AUTO_INCREMENT,
iUploadlogID bigint(20) NOT NULL DEFAULT '0',
cCustomeralias varchar(30) NOT NULL DEFAULT '',
cCustomercode varchar(30) NOT NULL DEFAULT '',
iCarrierID int(11) NOT NULL DEFAULT '0',
cScaccode varchar(20) NOT NULL DEFAULT '',
iOriginRegionID int(11) NOT NULL DEFAULT '0',
cOriginRegioncode varchar(20) NOT NULL DEFAULT '',
iOriginCountryID int(11) NOT NULL DEFAULT '0',
cOriginCountrycode varchar(20) NOT NULL DEFAULT '',
iOriginCFSUncodeID int(11) NOT NULL DEFAULT '0',
cOriginCFSUncode varchar(20) NOT NULL DEFAULT '',
iOriginConsoleCFSUncodeID int(11) NOT NULL DEFAULT '0',
cOriginConsoleCFSUncode varchar(20) NOT NULL DEFAULT '',
iOriginPortUncodeID int(11) NOT NULL DEFAULT '0',
cOriginPortUncode varchar(20) NOT NULL DEFAULT '',
cTransshipment_1 varchar(20) NOT NULL DEFAULT '',
cTransshipment_2 varchar(20) NOT NULL DEFAULT '',
cTransshipment_3 varchar(20) NOT NULL DEFAULT '',
iDestinationRegionID int(11) NOT NULL DEFAULT '0',
cDestinationRegioncode varchar(20) NOT NULL DEFAULT '',
iDestinationCountryID int(11) NOT NULL DEFAULT '0',
cDestinationCountrycode varchar(20) NOT NULL DEFAULT '',
iDestinationCFSUncodeID int(11) NOT NULL DEFAULT '0',
cDestinationCFSUncode varchar(20) NOT NULL DEFAULT '',
iDestinationDeconsoleCFSUncodeID int(11) NOT NULL DEFAULT '0',
cDestinationDeconsoleCFSUncode varchar(20) NOT NULL DEFAULT '',
iDestinationPortUncodeID int(11) NOT NULL DEFAULT '0',
cDestinationPortUncode varchar(20) NOT NULL DEFAULT '',
cQuotingregion varchar(20) NOT NULL DEFAULT '',
cTransittime varchar(10) NOT NULL DEFAULT '',
cOriginUncode varchar(20) NOT NULL DEFAULT '',
cDestinationUncode varchar(20) NOT NULL DEFAULT '',
cQuotingMember varchar(30) NOT NULL DEFAULT '',
cOriginKey varchar(100) NOT NULL DEFAULT '' COMMENT '$ = blank, - = separator',
cDestinationKey varchar(100) NOT NULL DEFAULT '' COMMENT '$ = blank, - = separator',
cTransshipmentKey varchar(100) NOT NULL DEFAULT '' COMMENT '$ = blank, - = separator',
iOriginKeyLength int(11) NOT NULL DEFAULT '0',
iDestinationKeyLength int(11) NOT NULL DEFAULT '0',
iTransshipmentKeyLength int(11) NOT NULL DEFAULT '0',
iStatus int(11) NOT NULL DEFAULT '0',
iActive int(4) NOT NULL DEFAULT '0',
iEnteredby int(11) NOT NULL DEFAULT '0',
tEntered datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
iUpdatedby int(11) NOT NULL DEFAULT '0',
tUpdated datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
PRIMARY KEY (iFreightOnBoardID)
);



CREATE TABLE IF NOT EXISTS grdb_FreightOnBoard_Charges_Write (
iFOBchargeID bigint(20) unsigned NOT NULL AUTO_INCREMENT,
iFreightOnBoardID bigint(20) unsigned NOT NULL DEFAULT '0',
iUploadlogID bigint(20) NOT NULL DEFAULT '0',
cCustomeralias varchar(20) NOT NULL DEFAULT '',
cScaccode varchar(20) NOT NULL DEFAULT '',
iCurrencyID int(11) NOT NULL DEFAULT '0',
cCurrency varchar(20) NOT NULL DEFAULT '',
iChargecodeID int(11) NOT NULL DEFAULT '0',
cChargecode varchar(20) NOT NULL DEFAULT '',
iRatebasisID int(11) NOT NULL DEFAULT '0',
cRatebasis varchar(20) NOT NULL DEFAULT '',
iRate double NOT NULL DEFAULT '0',
cFrom varchar(20) NOT NULL DEFAULT '',
cTo varchar(20) NOT NULL DEFAULT '',
iMinimum decimal(10,3) NOT NULL DEFAULT '0.000',
iMaximum decimal(10,3) NOT NULL DEFAULT '0.000',
cNotes text NOT NULL,
tEffectivedate date NOT NULL DEFAULT '0000-00-00',
tExpirationdate date NOT NULL DEFAULT '0000-00-00',
cVisible enum('Y','N') DEFAULT 'Y',
iStatus int(11) NOT NULL DEFAULT '0',
iActive int(4) NOT NULL DEFAULT '0',
iEnteredby int(11) NOT NULL DEFAULT '0',
tEntered datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
iUpdatedby int(11) NOT NULL DEFAULT '0',
tUpdated datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
PRIMARY KEY (iFOBchargeID)
);



CREATE TABLE IF NOT EXISTS grdb_FreightOnBoard_History (
iFOBHistoryID bigint(20) NOT NULL AUTO_INCREMENT,
iFreightOnBoardID bigint(20) NOT NULL DEFAULT '0',
iUploadlogID bigint(20) NOT NULL DEFAULT '0',
cCustomeralias varchar(30) NOT NULL DEFAULT '',
cCustomercode varchar(20) NOT NULL DEFAULT '',
iCarrierID int(11) NOT NULL DEFAULT '0',
cScaccode varchar(20) NOT NULL DEFAULT '',
iOriginRegionID int(11) NOT NULL DEFAULT '0',
cOriginRegioncode varchar(20) NOT NULL DEFAULT '',
iOriginCountryID int(11) NOT NULL DEFAULT '0',
cOriginCountrycode varchar(20) NOT NULL DEFAULT '',
iOriginCFSUncodeID int(11) NOT NULL DEFAULT '0',
cOriginCFSUncode varchar(20) NOT NULL DEFAULT '',
iOriginConsoleCFSUncodeID int(11) NOT NULL DEFAULT '0',
cOriginConsoleCFSUncode varchar(20) NOT NULL DEFAULT '',
iOriginPortUncodeID int(11) NOT NULL DEFAULT '0',
cOriginPortUncode varchar(20) NOT NULL DEFAULT '',
cTransshipment_1 varchar(20) NOT NULL DEFAULT '',
cTransshipment_2 varchar(20) NOT NULL DEFAULT '',
cTransshipment_3 varchar(20) NOT NULL DEFAULT '',
iDestinationRegionID int(11) NOT NULL DEFAULT '0',
cDestinationRegioncode varchar(20) NOT NULL DEFAULT '',
iDestinationCountryID int(11) NOT NULL DEFAULT '0',
cDestinationCountrycode varchar(20) NOT NULL DEFAULT '',
iDestinationCFSUncodeID int(11) NOT NULL DEFAULT '0',
cDestinationCFSUncode varchar(20) NOT NULL DEFAULT '',
iDestinationDeconsoleCFSUncodeID int(11) NOT NULL DEFAULT '0',
cDestinationDeconsoleCFSUncode varchar(20) NOT NULL DEFAULT '',
iDestinationPortUncodeID int(11) NOT NULL DEFAULT '0',
cDestinationPortUncode varchar(20) NOT NULL DEFAULT '',
cQuotingregion varchar(20) NOT NULL DEFAULT '',
cTransittime varchar(10) NOT NULL DEFAULT '',
cOriginUncode varchar(20) NOT NULL DEFAULT '',
cDestinationUncode varchar(20) NOT NULL DEFAULT '',
cQuotingMember varchar(30) NOT NULL DEFAULT '',
cOriginKey varchar(100) NOT NULL DEFAULT '' COMMENT '$ = blank, - = separator',
cDestinationKey varchar(100) NOT NULL DEFAULT '' COMMENT '$ = blank, - = separator',
cTransshipmentKey varchar(100) NOT NULL DEFAULT '' COMMENT '$ = blank, - = separator',
iStatus int(11) NOT NULL DEFAULT '0',
iActive int(4) NOT NULL DEFAULT '0',
iEnteredby int(11) NOT NULL DEFAULT '0',
tEntered datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
iUpdatedby int(11) NOT NULL DEFAULT '0',
tUpdated datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
PRIMARY KEY (iFOBHistoryID)
);



CREATE TABLE IF NOT EXISTS grdb_FreightOnBoard_Charges_History (
iFOBChargeHistoryID bigint(20) NOT NULL AUTO_INCREMENT,
iFOBHistoryID bigint(20) unsigned NOT NULL DEFAULT '0',
iFOBchargeID bigint(20) unsigned NOT NULL DEFAULT '0',
iFreightOnBoardID bigint(20) unsigned NOT NULL DEFAULT '0',
iUploadlogID bigint(20) NOT NULL DEFAULT '0',
cCustomeralias varchar(20) NOT NULL DEFAULT '',
cScaccode varchar(20) NOT NULL DEFAULT '',
iCurrencyID int(11) NOT NULL DEFAULT '0',
cCurrency varchar(20) NOT NULL DEFAULT '',
iChargecodeID int(11) NOT NULL DEFAULT '0',
cChargecode varchar(20) NOT NULL DEFAULT '',
iRatebasisID int(11) NOT NULL DEFAULT '0',
cRatebasis varchar(20) NOT NULL DEFAULT '',
iRate double NOT NULL DEFAULT '0',
cFrom varchar(20) NOT NULL DEFAULT '',
cTo varchar(20) NOT NULL DEFAULT '',
iMinimum decimal(10,3) NOT NULL DEFAULT '0.000',
iMaximum decimal(10,3) NOT NULL DEFAULT '0.000',
cNotes text NOT NULL,
tEffectivedate date NOT NULL DEFAULT '0000-00-00',
tExpirationdate date NOT NULL DEFAULT '0000-00-00',
cVisible enum('Y','N') DEFAULT 'Y',
iStatus int(11) NOT NULL DEFAULT '0',
iActive int(4) NOT NULL DEFAULT '0',
iEnteredby int(11) NOT NULL DEFAULT '0',
tEntered datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
iUpdatedby int(11) NOT NULL DEFAULT '0',
tUpdated datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
PRIMARY KEY (iFOBChargeHistoryID)
);



CREATE TABLE IF NOT EXISTS grdb_FreightOnBoard_History_Archive (
iFOBHistoryArchiveID bigint(20) NOT NULL AUTO_INCREMENT,
iFOBHistoryID bigint(20) NOT NULL DEFAULT '0',
iFreightOnBoardID bigint(20) NOT NULL DEFAULT '0',
iUploadlogID bigint(20) NOT NULL DEFAULT '0',
cCustomeralias varchar(30) NOT NULL DEFAULT '',
cCustomercode varchar(20) NOT NULL DEFAULT '',
iCarrierID int(11) NOT NULL DEFAULT '0',
cScaccode varchar(20) NOT NULL DEFAULT '',
iOriginRegionID int(11) NOT NULL DEFAULT '0',
cOriginRegioncode varchar(20) NOT NULL DEFAULT '',
iOriginCountryID int(11) NOT NULL DEFAULT '0',
cOriginCountrycode varchar(20) NOT NULL DEFAULT '',
iOriginCFSUncodeID int(11) NOT NULL DEFAULT '0',
cOriginCFSUncode varchar(20) NOT NULL DEFAULT '',
iOriginConsoleCFSUncodeID int(11) NOT NULL DEFAULT '0',
cOriginConsoleCFSUncode varchar(20) NOT NULL DEFAULT '',
iOriginPortUncodeID int(11) NOT NULL DEFAULT '0',
cOriginPortUncode varchar(20) NOT NULL DEFAULT '',
cTransshipment_1 varchar(20) NOT NULL DEFAULT '',
cTransshipment_2 varchar(20) NOT NULL DEFAULT '',
cTransshipment_3 varchar(20) NOT NULL DEFAULT '',
iDestinationRegionID int(11) NOT NULL DEFAULT '0',
cDestinationRegioncode varchar(20) NOT NULL DEFAULT '',
iDestinationCountryID int(11) NOT NULL DEFAULT '0',
cDestinationCountrycode varchar(20) NOT NULL DEFAULT '',
iDestinationCFSUncodeID int(11) NOT NULL DEFAULT '0',
cDestinationCFSUncode varchar(20) NOT NULL DEFAULT '',
iDestinationDeconsoleCFSUncodeID int(11) NOT NULL DEFAULT '0',
cDestinationDeconsoleCFSUncode varchar(20) NOT NULL DEFAULT '',
iDestinationPortUncodeID int(11) NOT NULL DEFAULT '0',
cDestinationPortUncode varchar(20) NOT NULL DEFAULT '',
cQuotingregion varchar(20) NOT NULL DEFAULT '',
cTransittime varchar(10) NOT NULL DEFAULT '',
cOriginUncode varchar(20) NOT NULL DEFAULT '',
cDestinationUncode varchar(20) NOT NULL DEFAULT '',
cQuotingMember varchar(30) NOT NULL DEFAULT '',
cOriginKey varchar(100) NOT NULL DEFAULT '' COMMENT '$ = blank, - = separator',
cDestinationKey varchar(100) NOT NULL DEFAULT '' COMMENT '$ = blank, - = separator',
cTransshipmentKey varchar(100) NOT NULL DEFAULT '' COMMENT '$ = blank, - = separator',
iStatus int(11) NOT NULL DEFAULT '0',
iActive int(4) NOT NULL DEFAULT '0',
iEnteredby int(11) NOT NULL DEFAULT '0',
tEntered datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
iUpdatedby int(11) NOT NULL DEFAULT '0',
tUpdated datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
PRIMARY KEY (iFOBHistoryArchiveID)
);



CREATE TABLE IF NOT EXISTS grdb_FreightOnBoard_Charges_History_Archive (
iFOBChargeHistoryArchiveID bigint(20) NOT NULL AUTO_INCREMENT,
iFOBHistoryArchiveID bigint(20) NOT NULL DEFAULT '0',
iFOBChargeHistoryID bigint(20) NOT NULL DEFAULT '0',
iFOBchargeID bigint(20) unsigned NOT NULL DEFAULT '0',
iFreightOnBoardID bigint(20) unsigned NOT NULL DEFAULT '0',
iUploadlogID bigint(20) NOT NULL DEFAULT '0',
cCustomeralias varchar(20) NOT NULL DEFAULT '',
cScaccode varchar(20) NOT NULL DEFAULT '',
iCurrencyID int(11) NOT NULL DEFAULT '0',
cCurrency varchar(20) NOT NULL DEFAULT '',
iChargecodeID int(11) NOT NULL DEFAULT '0',
cChargecode varchar(20) NOT NULL DEFAULT '',
iRatebasisID int(11) NOT NULL DEFAULT '0',
cRatebasis varchar(20) NOT NULL DEFAULT '',
iRate double NOT NULL DEFAULT '0',
cFrom varchar(20) NOT NULL DEFAULT '',
cTo varchar(20) NOT NULL DEFAULT '',
iMinimum decimal(10,3) NOT NULL DEFAULT '0.000',
iMaximum decimal(10,3) NOT NULL DEFAULT '0.000',
cNotes text NOT NULL,
tEffectivedate date NOT NULL DEFAULT '0000-00-00',
tExpirationdate date NOT NULL DEFAULT '0000-00-00',
cVisible enum('Y','N') DEFAULT 'Y',
iStatus int(11) NOT NULL DEFAULT '0',
iActive int(4) NOT NULL DEFAULT '0',
iEnteredby int(11) NOT NULL DEFAULT '0',
tEntered datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
iUpdatedby int(11) NOT NULL DEFAULT '0',
tUpdated datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
PRIMARY KEY (iFOBChargeHistoryArchiveID)
);



CREATE TABLE IF NOT EXISTS grdb_OceanFreight_Write (
iOceanFreightID bigint(20) NOT NULL AUTO_INCREMENT,
iUploadlogID bigint(20) NOT NULL DEFAULT '0',
cCustomeralias varchar(30) NOT NULL DEFAULT '',
cCustomercode varchar(30) NOT NULL DEFAULT '',
iCarrierID int(11) NOT NULL DEFAULT '0',
cScaccode varchar(20) NOT NULL DEFAULT '',
iOriginRegionID int(11) NOT NULL DEFAULT '0',
cOriginRegioncode varchar(20) NOT NULL DEFAULT '',
iOriginCountryID int(11) NOT NULL DEFAULT '0',
cOriginCountrycode varchar(20) NOT NULL DEFAULT '',
iOriginCFSUncodeID int(11) NOT NULL DEFAULT '0',
cOriginCFSUncode varchar(20) NOT NULL DEFAULT '',
iOriginConsoleCFSUncodeID int(11) NOT NULL DEFAULT '0',
cOriginConsoleCFSUncode varchar(20) NOT NULL DEFAULT '',
iOriginPortUncodeID int(11) NOT NULL DEFAULT '0',
cOriginPortUncode varchar(20) NOT NULL DEFAULT '',
cTransshipment_1 varchar(20) NOT NULL DEFAULT '',
cTransshipment_2 varchar(20) NOT NULL DEFAULT '',
cTransshipment_3 varchar(20) NOT NULL DEFAULT '',
iDestinationRegionID int(11) NOT NULL DEFAULT '0',
cDestinationRegioncode varchar(20) NOT NULL DEFAULT '',
iDestinationCountryID int(11) NOT NULL DEFAULT '0',
cDestinationCountrycode varchar(20) NOT NULL DEFAULT '',
iDestinationCFSUncodeID int(11) NOT NULL DEFAULT '0',
cDestinationCFSUncode varchar(20) NOT NULL DEFAULT '',
iDestinationDeconsoleCFSUncodeID int(11) NOT NULL DEFAULT '0',
cDestinationDeconsoleCFSUncode varchar(20) NOT NULL DEFAULT '',
iDestinationPortUncodeID int(11) NOT NULL DEFAULT '0',
cDestinationPortUncode varchar(20) NOT NULL DEFAULT '',
cQuotingregion varchar(20) NOT NULL DEFAULT '',
cTransittime varchar(10) NOT NULL DEFAULT '',
cOriginUncode varchar(20) NOT NULL DEFAULT '',
cDestinationUncode varchar(20) NOT NULL DEFAULT '',
cQuotingMember varchar(30) NOT NULL DEFAULT '',
cOriginKey varchar(100) NOT NULL DEFAULT '' COMMENT '$ = blank, - = separator',
cDestinationKey varchar(100) NOT NULL DEFAULT '' COMMENT '$ = blank, - = separator',
cTransshipmentKey varchar(100) NOT NULL DEFAULT '' COMMENT '$ = blank, - = separator',
iOriginKeyLength int(11) NOT NULL DEFAULT '0',
iDestinationKeyLength int(11) NOT NULL DEFAULT '0',
iTransshipmentKeyLength int(11) NOT NULL DEFAULT '0',
iOFRRate double NOT NULL DEFAULT '0',
iCurrencyID int(11) NOT NULL DEFAULT '0',
cCurrency varchar(20) NOT NULL DEFAULT '',
iChargecodeID int(11) NOT NULL DEFAULT '0',
cChargecode varchar(20) NOT NULL DEFAULT '',
iRatebasisID int(11) NOT NULL DEFAULT '0',
cRatebasis varchar(20) NOT NULL DEFAULT '',
cFrom int(11) NOT NULL DEFAULT '0',
cTo int(11) NOT NULL DEFAULT '0',
iMinimum decimal(10,3) NOT NULL DEFAULT '0.000',
iMaximum decimal(10,3) NOT NULL DEFAULT '0.000',
cNotes text NOT NULL,
tEffectivedate date NOT NULL DEFAULT '0000-00-00',
tExpirationdate date NOT NULL DEFAULT '0000-00-00',
cVisible enum('Y','N') DEFAULT 'Y',
nTotalRate double NOT NULL DEFAULT '0',
iFlag1 int(11) NOT NULL DEFAULT '0',
iFlag2 int(11) NOT NULL DEFAULT '0',
iStatus int(11) NOT NULL DEFAULT '0',
iActive int(4) NOT NULL DEFAULT '0',
iEnteredby int(11) NOT NULL DEFAULT '0',
tEntered datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
iUpdatedby int(11) NOT NULL DEFAULT '0',
tUpdated datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
PRIMARY KEY (iOceanFreightID)
);



CREATE TABLE IF NOT EXISTS grdb_OceanFreight_Charges_Write (
iOFRchargeID bigint(20) unsigned NOT NULL AUTO_INCREMENT,
iUploadlogID bigint(20) NOT NULL DEFAULT '0',
cCustomeralias varchar(20) NOT NULL DEFAULT '',
cScaccode varchar(20) NOT NULL DEFAULT '',
iOceanFreightID bigint(20) unsigned NOT NULL DEFAULT '0',
iCurrencyID int(11) NOT NULL DEFAULT '0',
cCurrency varchar(20) NOT NULL DEFAULT '',
iChargecodeID int(11) NOT NULL DEFAULT '0',
cChargecode varchar(20) NOT NULL DEFAULT '',
iRatebasisID int(11) NOT NULL DEFAULT '0',
cRatebasis varchar(20) NOT NULL DEFAULT '',
iRate double NOT NULL DEFAULT '0',
cFrom varchar(20) NOT NULL DEFAULT '',
cTo varchar(20) NOT NULL DEFAULT '',
iMinimum decimal(10,3) NOT NULL DEFAULT '0.000',
iMaximum decimal(10,3) NOT NULL DEFAULT '0.000',
cNotes text NOT NULL,
tEffectivedate date NOT NULL DEFAULT '0000-00-00',
tExpirationdate date NOT NULL DEFAULT '0000-00-00',
cVisible enum('Y','N') DEFAULT 'Y',
iStatus int(11) NOT NULL DEFAULT '0',
iActive int(4) NOT NULL DEFAULT '0',
iEnteredby int(11) NOT NULL DEFAULT '0',
tEntered datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
iUpdatedby int(11) NOT NULL DEFAULT '0',
tUpdated datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
PRIMARY KEY (iOFRchargeID)
);



CREATE TABLE IF NOT EXISTS grdb_OceanFreight_History (
iOceanFreightHistoryID bigint(20) NOT NULL AUTO_INCREMENT,
iOceanFreightID bigint(20) NOT NULL DEFAULT '0',
iUploadlogID bigint(20) NOT NULL DEFAULT '0',
cCustomeralias varchar(30) NOT NULL DEFAULT '',
cCustomercode varchar(20) NOT NULL DEFAULT '',
iCarrierID int(11) NOT NULL DEFAULT '0',
cScaccode varchar(20) NOT NULL DEFAULT '',
iOriginRegionID int(11) NOT NULL DEFAULT '0',
cOriginRegioncode varchar(20) NOT NULL DEFAULT '',
iOriginCountryID int(11) NOT NULL DEFAULT '0',
cOriginCountrycode varchar(20) NOT NULL DEFAULT '',
iOriginCFSUncodeID int(11) NOT NULL DEFAULT '0',
cOriginCFSUncode varchar(20) NOT NULL DEFAULT '',
iOriginConsoleCFSUncodeID int(11) NOT NULL DEFAULT '0',
cOriginConsoleCFSUncode varchar(20) NOT NULL DEFAULT '',
iOriginPortUncodeID int(11) NOT NULL DEFAULT '0',
cOriginPortUncode varchar(20) NOT NULL DEFAULT '',
cTransshipment_1 varchar(20) NOT NULL DEFAULT '',
cTransshipment_2 varchar(20) NOT NULL DEFAULT '',
cTransshipment_3 varchar(20) NOT NULL DEFAULT '',
iDestinationRegionID int(11) NOT NULL DEFAULT '0',
cDestinationRegioncode varchar(20) NOT NULL DEFAULT '',
iDestinationCountryID int(11) NOT NULL DEFAULT '0',
cDestinationCountrycode varchar(20) NOT NULL DEFAULT '',
iDestinationCFSUncodeID int(11) NOT NULL DEFAULT '0',
cDestinationCFSUncode varchar(20) NOT NULL DEFAULT '',
iDestinationDeconsoleCFSUncodeID int(11) NOT NULL DEFAULT '0',
cDestinationDeconsoleCFSUncode varchar(20) NOT NULL DEFAULT '',
iDestinationPortUncodeID int(11) NOT NULL DEFAULT '0',
cDestinationPortUncode varchar(20) NOT NULL DEFAULT '',
cQuotingregion varchar(20) NOT NULL DEFAULT '',
cTransittime varchar(10) NOT NULL DEFAULT '',
cOriginUncode varchar(10) NOT NULL DEFAULT '',
cDestinationUncode varchar(10) NOT NULL DEFAULT '',
cQuotingMember varchar(30) NOT NULL DEFAULT '',
cOriginKey varchar(100) NOT NULL DEFAULT '' COMMENT '$ = blank, - = separator',
cDestinationKey varchar(100) NOT NULL DEFAULT '' COMMENT '$ = blank, - = separator',
cTransshipmentKey varchar(100) NOT NULL DEFAULT '' COMMENT '$ = blank, - = separator',
iOFRRate double NOT NULL DEFAULT '0',
iCurrencyID int(11) NOT NULL DEFAULT '0',
cCurrency varchar(20) NOT NULL DEFAULT '',
iChargecodeID int(11) NOT NULL DEFAULT '0',
cChargecode varchar(20) NOT NULL DEFAULT '',
iRatebasisID int(11) NOT NULL DEFAULT '0',
cRatebasis varchar(20) NOT NULL DEFAULT '',
cFrom varchar(20) NOT NULL DEFAULT '',
cTo varchar(20) NOT NULL DEFAULT '',
iMinimum decimal(10,3) NOT NULL DEFAULT '0.000',
iMaximum decimal(10,3) NOT NULL DEFAULT '0.000',
cNotes text NOT NULL,
tEffectivedate date NOT NULL DEFAULT '0000-00-00',
tExpirationdate date NOT NULL DEFAULT '0000-00-00',
cVisible enum('Y','N') DEFAULT 'Y',
nTotalRate double NOT NULL DEFAULT '0',
iStatus int(11) NOT NULL DEFAULT '0',
iActive int(4) NOT NULL DEFAULT '0',
iEnteredby int(11) NOT NULL DEFAULT '0',
tEntered datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
iUpdatedby int(11) NOT NULL DEFAULT '0',
tUpdated datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
PRIMARY KEY (iOceanFreightHistoryID)
);



CREATE TABLE IF NOT EXISTS grdb_OceanFreight_Charges_History (
iOFRchargeHistoryID bigint unsigned NOT NULL AUTO_INCREMENT,
iOceanFreightHistoryID bigint NOT NULL DEFAULT '0',
iOFRchargeID bigint unsigned NOT NULL DEFAULT '0',
iOceanFreightID bigint unsigned NOT NULL DEFAULT '0',
iUploadlogID bigint NOT NULL DEFAULT '0',
cCustomeralias varchar(20) NOT NULL DEFAULT '',
cScaccode varchar(20) NOT NULL DEFAULT '',
iCurrencyID int NOT NULL DEFAULT '0',
cCurrency varchar(20) NOT NULL DEFAULT '',
iChargecodeID int NOT NULL DEFAULT '0',
cChargecode varchar(20) NOT NULL DEFAULT '',
iRatebasisID int NOT NULL DEFAULT '0',
cRatebasis varchar(20) NOT NULL DEFAULT '',
iRate double NOT NULL DEFAULT '0',
cFrom varchar(20) NOT NULL DEFAULT '',
cTo varchar(20) NOT NULL DEFAULT '',
iMinimum decimal(10,3) NOT NULL DEFAULT '0.000',
iMaximum decimal(10,3) NOT NULL DEFAULT '0.000',
cNotes text NOT NULL,
tEffectivedate date NOT NULL DEFAULT '0000-00-00',
tExpirationdate date NOT NULL DEFAULT '0000-00-00',
cVisible enum('Y','N') DEFAULT 'Y',
iStatus int NOT NULL DEFAULT '0',
iActive int NOT NULL DEFAULT '0',
iEnteredby int NOT NULL DEFAULT '0',
tEntered datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
iUpdatedby int NOT NULL DEFAULT '0',
tUpdated datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
PRIMARY KEY (iOFRchargeHistoryID)
);



CREATE TABLE IF NOT EXISTS grdb_OceanFreight_History_Archive (
iOceanFreightHistoryArchiveID bigint NOT NULL AUTO_INCREMENT,
iOceanFreightHistoryID bigint NOT NULL DEFAULT '0',
iOceanFreightID bigint NOT NULL DEFAULT '0',
iUploadlogID bigint NOT NULL DEFAULT '0',
cCustomeralias varchar(30) NOT NULL DEFAULT '',
cCustomercode varchar(20) NOT NULL DEFAULT '',
iCarrierID int NOT NULL DEFAULT '0',
cScaccode varchar(20) NOT NULL DEFAULT '',
iOriginRegionID int NOT NULL DEFAULT '0',
cOriginRegioncode varchar(20) NOT NULL DEFAULT '',
iOriginCountryID int NOT NULL DEFAULT '0',
cOriginCountrycode varchar(20) NOT NULL DEFAULT '',
iOriginCFSUncodeID int NOT NULL DEFAULT '0',
cOriginCFSUncode varchar(20) NOT NULL DEFAULT '',
iOriginConsoleCFSUncodeID int NOT NULL DEFAULT '0',
cOriginConsoleCFSUncode varchar(20) NOT NULL DEFAULT '',
iOriginPortUncodeID int NOT NULL DEFAULT '0',
cOriginPortUncode varchar(20) NOT NULL DEFAULT '',
cTransshipment_1 varchar(20) NOT NULL DEFAULT '',
cTransshipment_2 varchar(20) NOT NULL DEFAULT '',
cTransshipment_3 varchar(20) NOT NULL DEFAULT '',
iDestinationRegionID int NOT NULL DEFAULT '0',
cDestinationRegioncode varchar(20) NOT NULL DEFAULT '',
iDestinationCountryID int NOT NULL DEFAULT '0',
cDestinationCountrycode varchar(20) NOT NULL DEFAULT '',
iDestinationCFSUncodeID int NOT NULL DEFAULT '0',
cDestinationCFSUncode varchar(20) NOT NULL DEFAULT '',
iDestinationDeconsoleCFSUncodeID int NOT NULL DEFAULT '0',
cDestinationDeconsoleCFSUncode varchar(20) NOT NULL DEFAULT '',
iDestinationPortUncodeID int NOT NULL DEFAULT '0',
cDestinationPortUncode varchar(20) NOT NULL DEFAULT '',
cQuotingregion varchar(20) NOT NULL DEFAULT '',
cTransittime varchar(10) NOT NULL DEFAULT '',
cOriginUncode varchar(20) NOT NULL DEFAULT '',
cDestinationUncode varchar(20) NOT NULL DEFAULT '',
cQuotingMember varchar(30) NOT NULL DEFAULT '',
cOriginKey varchar(100) NOT NULL DEFAULT '' COMMENT '$ = blank, - = separator',
cDestinationKey varchar(100) NOT NULL DEFAULT '' COMMENT '$ = blank, - = separator',
cTransshipmentKey varchar(100) NOT NULL DEFAULT '' COMMENT '$ = blank, - = separator',
iOFRRate double NOT NULL DEFAULT '0',
iCurrencyID int NOT NULL DEFAULT '0',
cCurrency varchar(20) NOT NULL DEFAULT '',
iChargecodeID int NOT NULL DEFAULT '0',
cChargecode varchar(20) NOT NULL DEFAULT '',
iRatebasisID int NOT NULL DEFAULT '0',
cRatebasis varchar(20) NOT NULL DEFAULT '',
cFrom varchar(20) NOT NULL DEFAULT '',
cTo varchar(20) NOT NULL DEFAULT '',
iMinimum decimal(10,3) NOT NULL DEFAULT '0.000',
iMaximum decimal(10,3) NOT NULL DEFAULT '0.000',
cNotes text NOT NULL,
tEffectivedate date NOT NULL DEFAULT '0000-00-00',
tExpirationdate date NOT NULL DEFAULT '0000-00-00',
cVisible enum('Y','N') DEFAULT 'Y',
nTotalRate double NOT NULL DEFAULT '0',
iStatus int NOT NULL DEFAULT '0',
iActive int NOT NULL DEFAULT '0',
iEnteredby int NOT NULL DEFAULT '0',
tEntered datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
iUpdatedby int NOT NULL DEFAULT '0',
tUpdated datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
PRIMARY KEY (iOceanFreightHistoryArchiveID)
);



CREATE TABLE IF NOT EXISTS grdb_OceanFreight_Charges_History_Archive (
iOFRchargeHistoryArchiveID bigint(20) unsigned NOT NULL AUTO_INCREMENT,
iOceanFreightHistoryArchiveID bigint(20) NOT NULL DEFAULT '0',
iOFRchargeHistoryID bigint(20) unsigned NOT NULL DEFAULT '0',
iOFRchargeID bigint(20) unsigned NOT NULL DEFAULT '0',
iOceanFreightID bigint(20) unsigned NOT NULL DEFAULT '0',
iUploadlogID bigint(20) NOT NULL DEFAULT '0',
cCustomeralias varchar(20) NOT NULL DEFAULT '',
cScaccode varchar(20) NOT NULL DEFAULT '',
iCurrencyID int(11) NOT NULL DEFAULT '0',
cCurrency varchar(20) NOT NULL DEFAULT '',
iChargecodeID int(11) NOT NULL DEFAULT '0',
cChargecode varchar(20) NOT NULL DEFAULT '',
iRatebasisID int(11) NOT NULL DEFAULT '0',
cRatebasis varchar(20) NOT NULL DEFAULT '',
iRate double NOT NULL DEFAULT '0',
cFrom varchar(20) NOT NULL DEFAULT '',
cTo varchar(20) NOT NULL DEFAULT '',
iMinimum decimal(10,3) NOT NULL DEFAULT '0.000',
iMaximum decimal(10,3) NOT NULL DEFAULT '0.000',
cNotes text NOT NULL,
tEffectivedate date NOT NULL DEFAULT '0000-00-00',
tExpirationdate date NOT NULL DEFAULT '0000-00-00',
cVisible enum('Y','N') DEFAULT 'Y',
iStatus int(11) NOT NULL DEFAULT '0',
iActive int(4) NOT NULL DEFAULT '0',
iEnteredby int(11) NOT NULL DEFAULT '0',
tEntered datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
iUpdatedby int(11) NOT NULL DEFAULT '0',
tUpdated datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
PRIMARY KEY (iOFRchargeHistoryArchiveID)
);



CREATE TABLE IF NOT EXISTS grdb_Postlanding_Write (
iPostlandingID bigint NOT NULL AUTO_INCREMENT,
iUploadlogID bigint NOT NULL DEFAULT '0',
cCustomeralias varchar(30) NOT NULL DEFAULT '',
cCustomercode varchar(30) NOT NULL DEFAULT '',
iCarrierID int NOT NULL DEFAULT '0',
cScaccode varchar(20) NOT NULL DEFAULT '',
iOriginRegionID int NOT NULL DEFAULT '0',
cOriginRegioncode varchar(20) NOT NULL DEFAULT '',
iOriginCountryID int NOT NULL DEFAULT '0',
cOriginCountrycode varchar(20) NOT NULL DEFAULT '',
iOriginCFSUncodeID int NOT NULL DEFAULT '0',
cOriginCFSUncode varchar(20) NOT NULL DEFAULT '',
iOriginConsoleCFSUncodeID int NOT NULL DEFAULT '0',
cOriginConsoleCFSUncode varchar(20) NOT NULL DEFAULT '',
iOriginPortUncodeID int NOT NULL DEFAULT '0',
cOriginPortUncode varchar(20) NOT NULL DEFAULT '',
cTransshipment_1 varchar(20) NOT NULL DEFAULT '',
cTransshipment_2 varchar(20) NOT NULL DEFAULT '',
cTransshipment_3 varchar(20) NOT NULL DEFAULT '',
iDestinationRegionID int NOT NULL DEFAULT '0',
cDestinationRegioncode varchar(20) NOT NULL DEFAULT '',
iDestinationCountryID int NOT NULL DEFAULT '0',
cDestinationCountrycode varchar(20) NOT NULL DEFAULT '',
iDestinationCFSUncodeID int NOT NULL DEFAULT '0',
cDestinationCFSUncode varchar(20) NOT NULL DEFAULT '',
iDestinationDeconsoleCFSUncodeID int NOT NULL DEFAULT '0',
cDestinationDeconsoleCFSUncode varchar(20) NOT NULL DEFAULT '',
iDestinationPortUncodeID int NOT NULL DEFAULT '0',
cDestinationPortUncode varchar(20) NOT NULL DEFAULT '',
cQuotingregion varchar(20) NOT NULL DEFAULT '',
cTransittime varchar(10) NOT NULL DEFAULT '',
cOriginUncode varchar(20) NOT NULL DEFAULT '',
cDestinationUncode varchar(20) NOT NULL DEFAULT '',
cQuotingMember varchar(30) NOT NULL DEFAULT '',
cOriginKey varchar(100) NOT NULL DEFAULT '' COMMENT '$ = blank, - = separator',
cDestinationKey varchar(100) NOT NULL DEFAULT '' COMMENT '$ = blank, - = separator',
cTransshipmentKey varchar(100) NOT NULL DEFAULT '' COMMENT '$ = blank, - = separator',
iOriginKeyLength int NOT NULL DEFAULT '0',
iDestinationKeyLength int NOT NULL DEFAULT '0',
iTransshipmentKeyLength int NOT NULL DEFAULT '0',
iStatus int NOT NULL DEFAULT '0',
iActive int NOT NULL DEFAULT '0',
iEnteredby int NOT NULL DEFAULT '0',
tEntered datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
iUpdatedby int NOT NULL DEFAULT '0',
tUpdated datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
PRIMARY KEY (iPostlandingID)
);



CREATE TABLE IF NOT EXISTS grdb_Postlanding_Charges_Write (
iPLCchargeID bigint(20) unsigned NOT NULL AUTO_INCREMENT,
iPostlandingID bigint(20) unsigned NOT NULL DEFAULT '0',
iUploadlogID bigint(20) NOT NULL DEFAULT '0',
cCustomeralias varchar(20) NOT NULL DEFAULT '',
cScaccode varchar(20) NOT NULL DEFAULT '',
iCurrencyID int(11) NOT NULL DEFAULT '0',
cCurrency varchar(20) NOT NULL DEFAULT '',
iChargecodeID int(11) NOT NULL DEFAULT '0',
cChargecode varchar(20) NOT NULL DEFAULT '',
iRatebasisID int(11) NOT NULL DEFAULT '0',
cRatebasis varchar(20) NOT NULL DEFAULT '',
iRate double NOT NULL DEFAULT '0',
cFrom varchar(20) NOT NULL DEFAULT '',
cTo varchar(20) NOT NULL DEFAULT '',
iMinimum decimal(10,3) NOT NULL DEFAULT '0.000',
iMaximum decimal(10,3) NOT NULL DEFAULT '0.000',
cNotes text NOT NULL,
tEffectivedate date NOT NULL DEFAULT '0000-00-00',
tExpirationdate date NOT NULL DEFAULT '0000-00-00',
cVisible enum('Y','N') DEFAULT 'Y',
iStatus int(11) NOT NULL DEFAULT '0',
iActive int(4) NOT NULL DEFAULT '0',
iEnteredby int(11) NOT NULL DEFAULT '0',
tEntered datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
iUpdatedby int(11) NOT NULL DEFAULT '0',
tUpdated datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
PRIMARY KEY (iPLCchargeID)
);



CREATE TABLE IF NOT EXISTS grdb_Postlanding_History (
iPostlandingHistoryID bigint(20) NOT NULL AUTO_INCREMENT,
iPostlandingID bigint(20) NOT NULL DEFAULT '0',
iUploadlogID bigint(20) NOT NULL DEFAULT '0',
cCustomeralias varchar(30) NOT NULL DEFAULT '',
cCustomercode varchar(20) NOT NULL DEFAULT '',
iCarrierID int(11) NOT NULL DEFAULT '0',
cScaccode varchar(20) NOT NULL DEFAULT '',
iOriginRegionID int(11) NOT NULL DEFAULT '0',
cOriginRegioncode varchar(20) NOT NULL DEFAULT '',
iOriginCountryID int(11) NOT NULL DEFAULT '0',
cOriginCountrycode varchar(20) NOT NULL DEFAULT '',
iOriginCFSUncodeID int(11) NOT NULL DEFAULT '0',
cOriginCFSUncode varchar(20) NOT NULL DEFAULT '',
iOriginConsoleCFSUncodeID int(11) NOT NULL DEFAULT '0',
cOriginConsoleCFSUncode varchar(20) NOT NULL DEFAULT '',
iOriginPortUncodeID int(11) NOT NULL DEFAULT '0',
cOriginPortUncode varchar(20) NOT NULL DEFAULT '',
cTransshipment_1 varchar(20) NOT NULL DEFAULT '',
cTransshipment_2 varchar(20) NOT NULL DEFAULT '',
cTransshipment_3 varchar(20) NOT NULL DEFAULT '',
iDestinationRegionID int(11) NOT NULL DEFAULT '0',
cDestinationRegioncode varchar(20) NOT NULL DEFAULT '',
iDestinationCountryID int(11) NOT NULL DEFAULT '0',
cDestinationCountrycode varchar(20) NOT NULL DEFAULT '',
iDestinationCFSUncodeID int(11) NOT NULL DEFAULT '0',
cDestinationCFSUncode varchar(20) NOT NULL DEFAULT '',
iDestinationDeconsoleCFSUncodeID int(11) NOT NULL DEFAULT '0',
cDestinationDeconsoleCFSUncode varchar(20) NOT NULL DEFAULT '',
iDestinationPortUncodeID int(11) NOT NULL DEFAULT '0',
cDestinationPortUncode varchar(20) NOT NULL DEFAULT '',
cQuotingregion varchar(20) NOT NULL DEFAULT '',
cTransittime varchar(10) NOT NULL DEFAULT '',
cOriginUncode varchar(20) NOT NULL DEFAULT '',
cDestinationUncode varchar(20) NOT NULL DEFAULT '',
cQuotingMember varchar(30) NOT NULL DEFAULT '',
cOriginKey varchar(100) NOT NULL DEFAULT '' COMMENT '$ = blank, - = separator',
cDestinationKey varchar(100) NOT NULL DEFAULT '' COMMENT '$ = blank, - = separator',
cTransshipmentKey varchar(100) NOT NULL DEFAULT '' COMMENT '$ = blank, - = separator',
iStatus int(11) NOT NULL DEFAULT '0',
iActive int(4) NOT NULL DEFAULT '0',
iEnteredby int(11) NOT NULL DEFAULT '0',
tEntered datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
iUpdatedby int(11) NOT NULL DEFAULT '0',
tUpdated datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
PRIMARY KEY (iPostlandingHistoryID)
);



CREATE TABLE IF NOT EXISTS grdb_Postlanding_Charges_History (
iPLCchargeHistoryID bigint(20) unsigned NOT NULL AUTO_INCREMENT,
iPostlandingHistoryID bigint(20) NOT NULL DEFAULT '0',
iPLCchargeID bigint(20) unsigned NOT NULL DEFAULT '0',
iPostlandingID bigint(20) unsigned NOT NULL DEFAULT '0',
iUploadlogID bigint(20) NOT NULL DEFAULT '0',
cCustomeralias varchar(20) NOT NULL DEFAULT '',
cScaccode varchar(20) NOT NULL DEFAULT '',
iCurrencyID int(11) NOT NULL DEFAULT '0',
cCurrency varchar(20) NOT NULL DEFAULT '',
iChargecodeID int(11) NOT NULL DEFAULT '0',
cChargecode varchar(20) NOT NULL DEFAULT '',
iRatebasisID int(11) NOT NULL DEFAULT '0',
cRatebasis varchar(20) NOT NULL DEFAULT '',
iRate double NOT NULL DEFAULT '0',
cFrom varchar(20) NOT NULL DEFAULT '',
cTo varchar(20) NOT NULL DEFAULT '',
iMinimum decimal(10,3) NOT NULL DEFAULT '0.000',
iMaximum decimal(10,3) NOT NULL DEFAULT '0.000',
cNotes text NOT NULL,
tEffectivedate date NOT NULL DEFAULT '0000-00-00',
tExpirationdate date NOT NULL DEFAULT '0000-00-00',
cVisible enum('Y','N') DEFAULT 'Y',
iStatus int(11) NOT NULL DEFAULT '0',
iActive int(4) NOT NULL DEFAULT '0',
iEnteredby int(11) NOT NULL DEFAULT '0',
tEntered datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
iUpdatedby int(11) NOT NULL DEFAULT '0',
tUpdated datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
PRIMARY KEY (iPLCchargeHistoryID)
);



CREATE TABLE IF NOT EXISTS grdb_Postlanding_History_Archive (
iPostlandingHistoryArchiveID bigint(20) NOT NULL AUTO_INCREMENT,
iPostlandingHistoryID bigint(20) NOT NULL DEFAULT '0',
iPostlandingID bigint(20) NOT NULL DEFAULT '0',
iUploadlogID bigint(20) NOT NULL DEFAULT '0',
cCustomeralias varchar(30) NOT NULL DEFAULT '',
cCustomercode varchar(20) NOT NULL DEFAULT '',
iCarrierID int(11) NOT NULL DEFAULT '0',
cScaccode varchar(20) NOT NULL DEFAULT '',
iOriginRegionID int(11) NOT NULL DEFAULT '0',
cOriginRegioncode varchar(20) NOT NULL DEFAULT '',
iOriginCountryID int(11) NOT NULL DEFAULT '0',
cOriginCountrycode varchar(20) NOT NULL DEFAULT '',
iOriginCFSUncodeID int(11) NOT NULL DEFAULT '0',
cOriginCFSUncode varchar(20) NOT NULL DEFAULT '',
iOriginConsoleCFSUncodeID int(11) NOT NULL DEFAULT '0',
cOriginConsoleCFSUncode varchar(20) NOT NULL DEFAULT '',
iOriginPortUncodeID int(11) NOT NULL DEFAULT '0',
cOriginPortUncode varchar(20) NOT NULL DEFAULT '',
cTransshipment_1 varchar(20) NOT NULL DEFAULT '',
cTransshipment_2 varchar(20) NOT NULL DEFAULT '',
cTransshipment_3 varchar(20) NOT NULL DEFAULT '',
iDestinationRegionID int(11) NOT NULL DEFAULT '0',
cDestinationRegioncode varchar(20) NOT NULL DEFAULT '',
iDestinationCountryID int(11) NOT NULL DEFAULT '0',
cDestinationCountrycode varchar(20) NOT NULL DEFAULT '',
iDestinationCFSUncodeID int(11) NOT NULL DEFAULT '0',
cDestinationCFSUncode varchar(20) NOT NULL DEFAULT '',
iDestinationDeconsoleCFSUncodeID int(11) NOT NULL DEFAULT '0',
cDestinationDeconsoleCFSUncode varchar(20) NOT NULL DEFAULT '',
iDestinationPortUncodeID int(11) NOT NULL DEFAULT '0',
cDestinationPortUncode varchar(20) NOT NULL DEFAULT '',
cQuotingregion varchar(20) NOT NULL DEFAULT '',
cTransittime varchar(10) NOT NULL DEFAULT '',
cOriginUncode varchar(20) NOT NULL DEFAULT '',
cDestinationUncode varchar(20) NOT NULL DEFAULT '',
cQuotingMember varchar(30) NOT NULL DEFAULT '',
cOriginKey varchar(100) NOT NULL DEFAULT '' COMMENT '$ = blank, - = separator',
cDestinationKey varchar(100) NOT NULL DEFAULT '' COMMENT '$ = blank, - = separator',
cTransshipmentKey varchar(100) NOT NULL DEFAULT '' COMMENT '$ = blank, - = separator',
iStatus int(11) NOT NULL DEFAULT '0',
iActive int(4) NOT NULL DEFAULT '0',
iEnteredby int(11) NOT NULL DEFAULT '0',
tEntered datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
iUpdatedby int(11) NOT NULL DEFAULT '0',
tUpdated datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
PRIMARY KEY (iPostlandingHistoryArchiveID)
);



CREATE TABLE IF NOT EXISTS grdb_Postlanding_Charges_History_Archive (
iPLCchargeHistoryArchiveID bigint(20) unsigned NOT NULL AUTO_INCREMENT,
iPostlandingHistoryArchiveID bigint(20) NOT NULL DEFAULT '0',
iPLCchargeHistoryID bigint(20) unsigned NOT NULL DEFAULT '0',
iPLCchargeID bigint(20) unsigned NOT NULL DEFAULT '0',
iPostlandingID bigint(20) unsigned NOT NULL DEFAULT '0',
iUploadlogID bigint(20) NOT NULL DEFAULT '0',
cCustomeralias varchar(20) NOT NULL DEFAULT '',
cScaccode varchar(20) NOT NULL DEFAULT '',
iCurrencyID int(11) NOT NULL DEFAULT '0',
cCurrency varchar(20) NOT NULL DEFAULT '',
iChargecodeID int(11) NOT NULL DEFAULT '0',
cChargecode varchar(20) NOT NULL DEFAULT '',
iRatebasisID int(11) NOT NULL DEFAULT '0',
cRatebasis varchar(20) NOT NULL DEFAULT '',
iRate double NOT NULL DEFAULT '0',
cFrom varchar(20) NOT NULL DEFAULT '',
cTo varchar(20) NOT NULL DEFAULT '',
iMinimum decimal(10,3) NOT NULL DEFAULT '0.000',
iMaximum decimal(10,3) NOT NULL DEFAULT '0.000',
cNotes text NOT NULL,
tEffectivedate date NOT NULL DEFAULT '0000-00-00',
tExpirationdate date NOT NULL DEFAULT '0000-00-00',
cVisible enum('Y','N') DEFAULT 'Y',
iStatus int(11) NOT NULL DEFAULT '0',
iActive int(4) NOT NULL DEFAULT '0',
iEnteredby int(11) NOT NULL DEFAULT '0',
tEntered datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
iUpdatedby int(11) NOT NULL DEFAULT '0',
tUpdated datetime NOT NULL DEFAULT '0000-00-00 00:00:00',
PRIMARY KEY (iPLCchargeHistoryArchiveID)
);



CREATE TABLE IF NOT EXISTS rules (
id int NOT NULL AUTO_INCREMENT,
rule_name varchar(100) NOT NULL,
rule_des varchar(2000) NOT NULL,
rule_for varchar(100) NOT NULL,
table_name varchar(100) DEFAULT NULL,
table_col_names varchar(250) DEFAULT NULL,
sheet_col_name text,
val_type enum('BASIC_VAL','DB_VAL') DEFAULT 'BASIC_VAL',
PRIMARY KEY (id)
);



CREATE TABLE IF NOT EXISTS error_log (
id int NOT NULL AUTO_INCREMENT,
test_id int NOT NULL,
job_id int NOT NULL,
file_type varchar(45) NOT NULL,
spreadsheet_name varchar(45) NOT NULL,
file_name varchar(200) NOT NULL,
error_row_num int NOT NULL,
comment text NOT NULL,
process_start_time datetime(6) NOT NULL,
link varchar(200) NOT NULL,
process_end_time datetime(6) NOT NULL,
update_at datetime(6) NOT NULL,
warnings varchar(500) DEFAULT NULL,
PRIMARY KEY (id)
);



CREATE TABLE IF NOT EXISTS gen_Basis (
iBasisID int NOT NULL AUTO_INCREMENT,
cBasis varchar(10) DEFAULT NULL,
cCode varchar(10) DEFAULT NULL,
cName varchar(100) DEFAULT NULL,
cComment varchar(255) DEFAULT NULL,
iBasisGroupID int DEFAULT NULL,
cGlobalConversion varchar(255) DEFAULT NULL,
cCSRFQConversion varchar(255) DEFAULT NULL,
bInland tinyint(1) DEFAULT NULL,
cWeightRange enum('Y','N') DEFAULT NULL,
cCubeRange enum('Y','N') DEFAULT NULL,
cPriorityOFR varchar(15) DEFAULT NULL,
cPriorityFOB varchar(15) DEFAULT NULL,
cPriorityPLC varchar(15) DEFAULT NULL,
iStatus int DEFAULT NULL,
iEnteredby int DEFAULT NULL,
tEntered datetime DEFAULT NULL,
iUpdatedby int DEFAULT NULL,
tUpdated datetime DEFAULT NULL,
PRIMARY KEY (iBasisID)
);



CREATE TABLE IF NOT EXISTS gen_Carrier (
iCarrierID int NOT NULL AUTO_INCREMENT,
cCode varchar(5) DEFAULT NULL,
cScaccodeType enum('A','C','V') DEFAULT NULL,
cName varchar(50) DEFAULT NULL,
cPreference char(3) DEFAULT NULL,
cComments text,
cWww varchar(50) DEFAULT NULL,
cSchedule varchar(200) DEFAULT NULL,
iStatus int DEFAULT NULL,
iEnteredby int DEFAULT NULL,
tEntered datetime DEFAULT NULL,
iUpdatedby int DEFAULT NULL,
tUpdated datetime DEFAULT NULL,
PRIMARY KEY (iCarrierID)
);



CREATE TABLE IF NOT EXISTS gen_Chargecode (
iChargecodeID int NOT NULL AUTO_INCREMENT,
cCode char(4) DEFAULT NULL,
cName char(50) DEFAULT NULL,
cDefault enum('Y','N') DEFAULT NULL,
iStatus int DEFAULT NULL,
iEnteredby int DEFAULT NULL,
tEntered datetime DEFAULT NULL,
iUpdatedby int DEFAULT NULL,
tUpdated datetime DEFAULT NULL,
PRIMARY KEY (iChargecodeID)
);



CREATE TABLE IF NOT EXISTS gen_Country (
iCountryID int NOT NULL AUTO_INCREMENT,
iRegionID int DEFAULT NULL,
cCode char(2) DEFAULT NULL,
cName varchar(50) DEFAULT NULL,
cCurrencycode char(10) DEFAULT NULL,
cFclCurrencycode char(10) DEFAULT NULL,
cAesdescription text,
cAesspecialdescription text,
cConditions text,
cConditionsfcl text,
cConditionsair text,
cAesflag varchar(100) DEFAULT NULL,
cAesoption1 varchar(200) DEFAULT NULL,
cAesvalue1 varchar(50) DEFAULT NULL,
cAesoption2 varchar(200) DEFAULT NULL,
cAesvalue2 varchar(50) DEFAULT NULL,
cAesoption3 varchar(200) DEFAULT NULL,
cAesvalue3 varchar(50) DEFAULT NULL,
cAesoption4 varchar(200) DEFAULT NULL,
cAesvalue4 varchar(50) DEFAULT NULL,
cAesoption5 varchar(200) DEFAULT NULL,
cAesvalue5 varchar(50) DEFAULT NULL,
cAesstring varchar(200) DEFAULT NULL,
cCc varchar(200) DEFAULT NULL,
cDefaultcountry enum('N','Y') DEFAULT NULL,
cAes enum('N','Y') DEFAULT NULL,
cAesspecial enum('N','Y') DEFAULT NULL,
cLclrate enum('N','Y') DEFAULT NULL,
cLicensedcargo enum('N','Y') DEFAULT NULL,
cDialingcode char(5) DEFAULT NULL,
cInlandType varchar(10) DEFAULT NULL,
cIsRestricted enum('N','Y') DEFAULT NULL,
bCurrencyConversion tinyint(1) DEFAULT NULL,
iStatus int DEFAULT NULL,
iEnteredby int DEFAULT NULL,
tEntered datetime DEFAULT NULL,
iUpdatedby int DEFAULT NULL,
tUpdated datetime DEFAULT NULL,
PRIMARY KEY (iCountryID)
);



CREATE TABLE IF NOT EXISTS gen_Currency_exchange_rate (
iCurrencyexchangerateID bigint NOT NULL AUTO_INCREMENT,
cCurrencyfrom char(4) DEFAULT NULL,
cCurrencyto char(4) DEFAULT NULL,
dExchangerate double(20,6) DEFAULT NULL,
tEffectivedate date DEFAULT NULL,
dBuyexchangerate double(20,6) DEFAULT NULL,
cEffectivetime time DEFAULT NULL,
cTimezone char(3) DEFAULT NULL,
iStatus int DEFAULT NULL,
iEnteredby int DEFAULT NULL,
tEntered datetime DEFAULT NULL,
iUpdatedby int DEFAULT NULL,
tUpdated datetime DEFAULT NULL,
PRIMARY KEY (iCurrencyexchangerateID)
);



CREATE TABLE IF NOT EXISTS gen_Customer_alias (
iCustomeraliasID int NOT NULL,
cAliascode varchar(20) DEFAULT NULL,
cAliasname varchar(100) DEFAULT NULL,
cValidationrule varchar(3) DEFAULT NULL,
iLogoID int DEFAULT NULL,
iMemberID int DEFAULT NULL,
cCmsagent varchar(15) DEFAULT NULL,
cIsGroup enum('Y','N') DEFAULT NULL,
cIsGrdb enum('Y','N') DEFAULT NULL,
cRateDeleteFlag enum('Y','N') DEFAULT NULL,
cCustomerType varchar(11) DEFAULT NULL,
cIsDelete enum('Y','N') DEFAULT NULL,
cIsPrivate enum('Y','N') DEFAULT NULL,
cIsAutorenewal enum('Y','N') DEFAULT NULL,
cIsSpecial enum('Y','N') DEFAULT NULL,
cActivateThirdpartyCharges enum('Y','N') DEFAULT NULL,
iStatus int DEFAULT NULL,
iEnteredby int DEFAULT NULL,
tEntered datetime DEFAULT NULL,
iUpdatedby int DEFAULT NULL,
tUpdated datetime DEFAULT NULL,
PRIMARY KEY (iCustomeraliasID)
);



CREATE TABLE IF NOT EXISTS gen_Location (
iLocationID int NOT NULL AUTO_INCREMENT,
iStateID int DEFAULT NULL,
iWarehouseexpID int DEFAULT NULL,
iWarehouseimpID int DEFAULT NULL,
cCode char(5) DEFAULT NULL,
cCountrycode char(2) DEFAULT NULL,
cCitycode char(3) DEFAULT NULL,
cAltcitycode char(3) DEFAULT NULL,
cCityname char(50) DEFAULT NULL,
cAltcityname char(50) DEFAULT NULL,
cLclregion char(50) DEFAULT NULL,
cLclorigin char(50) DEFAULT NULL,
cLatitude varchar(10) DEFAULT NULL,
cLongitude varchar(10) DEFAULT NULL,
cLocationtype char(50) DEFAULT NULL,
iTimezoneID int DEFAULT NULL,
cZipcode varchar(15) DEFAULT NULL,
cDialingcode char(5) DEFAULT NULL,
iIsPortFlag tinyint(1) DEFAULT NULL,
cActive enum('N','Y') DEFAULT NULL,
cOceanlocation enum('N','Y') DEFAULT NULL,
cAirlocation enum('N','Y') DEFAULT NULL,
cRaillocation enum('N','Y') DEFAULT NULL,
cCfslocation enum('N','Y') DEFAULT NULL,
iStatus int DEFAULT NULL,
iEnteredby int DEFAULT NULL,
tEntered datetime DEFAULT NULL,
iUpdatedby int DEFAULT NULL,
tUpdated datetime DEFAULT NULL,
PRIMARY KEY (iLocationID)
);



CREATE TABLE IF NOT EXISTS gen_Region (
iRegionID int NOT NULL,
iUserID int DEFAULT NULL,
cCode varchar(30) DEFAULT NULL,
cName varchar(30) DEFAULT NULL,
iStatus int DEFAULT NULL,
iEnteredBy int DEFAULT NULL,
tEntered datetime DEFAULT NULL,
iUpdatedBy int DEFAULT NULL,
tUpdated datetime DEFAULT NULL,
PRIMARY KEY (iRegionID)
);



CREATE TABLE IF NOT EXISTS grdb_Locking_Customers (
iLockCustomerID bigint unsigned NOT NULL AUTO_INCREMENT,
iUploadlogID int DEFAULT NULL,
cCustomeralias varchar(20) DEFAULT NULL,
cRateType enum('OFR','FOB','PLC') DEFAULT NULL,
cLocked enum('Y','N') DEFAULT NULL,
iStatus int DEFAULT NULL,
iEnteredby int DEFAULT NULL,
tEntered datetime DEFAULT NULL,
iUpdatedby int DEFAULT NULL,
tUpdated datetime DEFAULT NULL,
PRIMARY KEY (iLockCustomerID)
);



CREATE TABLE IF NOT EXISTS grdb_Locking_Tradelanes (
iTradelaneID bigint NOT NULL,
iLockCustomerID bigint DEFAULT NULL,
iUploadlogID int DEFAULT NULL,
iOriginregion int DEFAULT NULL,
cOriginregioncode varchar(20) DEFAULT NULL,
iOriginCountryID int DEFAULT NULL,
cOriginCountrycode varchar(20) DEFAULT NULL,
iOriginUncodeID int DEFAULT NULL,
cOriginUncode varchar(20) DEFAULT NULL,
iDestinationregion int DEFAULT NULL,
cDestinationregioncode varchar(20) DEFAULT NULL,
iDestinationCountryID int DEFAULT NULL,
cDestinationCountrycode varchar(20) DEFAULT NULL,
iDestinationUncodeID int DEFAULT NULL,
cDestinationUncode varchar(20) DEFAULT NULL,
tFromDate date DEFAULT NULL,
tToDate date DEFAULT NULL,
cLocked enum('Y','N') DEFAULT NULL,
cFilteredType varchar(50) DEFAULT NULL,
cOptionalColumn1 varchar(255) DEFAULT NULL,
cOptionalColumn2 varchar(255) DEFAULT NULL,
cOptionalColumn3 varchar(255) DEFAULT NULL,
iStatus int DEFAULT NULL,
iEnteredby int DEFAULT NULL,
tEntered datetime DEFAULT NULL,
iUpdatedby int DEFAULT NULL,
tUpdated datetime DEFAULT NULL,
PRIMARY KEY (iTradelaneID)
);



CREATE TABLE IF NOT EXISTS grdb_Routing_Customer_Mapping (
iMappingID int NOT NULL AUTO_INCREMENT,
iRoutingGuideID int DEFAULT NULL,
cCustomeralias varchar(20) DEFAULT NULL,
cOriginUncode varchar(20) DEFAULT NULL,
cDestinationUncode varchar(20) DEFAULT NULL,
iStatus int DEFAULT NULL,
iEnteredby int DEFAULT NULL,
tEntered datetime DEFAULT NULL,
iUpdatedby int DEFAULT NULL,
tUpdated datetime DEFAULT NULL,
PRIMARY KEY (iMappingID)
);



CREATE TABLE IF NOT EXISTS grdb_RoutingGuide (
iRoutingGuideID int NOT NULL AUTO_INCREMENT,
iOriginRegionID int DEFAULT NULL,
cOriginRegioncode varchar(20) DEFAULT NULL,
iOriginCountryID int DEFAULT NULL,
cOriginCountrycode varchar(20) DEFAULT NULL,
iOriginUncodeID int DEFAULT NULL,
cOriginUncode varchar(20) DEFAULT NULL,
iDestinationRegionID int DEFAULT NULL,
cDestinationRegioncode varchar(20) DEFAULT NULL,
iDestinationCountryID int DEFAULT NULL,
cDestinationCountrycode varchar(20) DEFAULT NULL,
iDestinationUncodeID int DEFAULT NULL,
cDestinationUncode varchar(20) DEFAULT NULL,
iOFRCarrierID int DEFAULT NULL,
cOFRScaccode varchar(20) DEFAULT NULL,
iFOBCarrierID int DEFAULT NULL,
cFOBScaccode varchar(20) DEFAULT NULL,
iPLCCarrierID int DEFAULT NULL,
cPLCScaccode varchar(20) DEFAULT NULL,
cOFRSheetcode varchar(30) DEFAULT NULL,
cFOBSheetcode varchar(30) DEFAULT NULL,
cPLCSheetcode varchar(30) DEFAULT NULL,
iFOBType tinyint DEFAULT NULL,
iOFRType tinyint DEFAULT NULL,
iPLCType tinyint DEFAULT NULL,
cRateType varchar(50) DEFAULT NULL,
cType enum('WO','WE') DEFAULT NULL,
iFOBMissing tinyint DEFAULT NULL,
iOFRMissing tinyint DEFAULT NULL,
iPLCMissing tinyint DEFAULT NULL,
cCustomeralias varchar(50) DEFAULT NULL,
cISAccurate varchar(11) DEFAULT NULL,
cISSchedule varchar(11) DEFAULT NULL,
cOption1 varchar(255) DEFAULT NULL,
cOption2 varchar(255) DEFAULT NULL,
cOption3 varchar(255) DEFAULT NULL,
iStatus tinyint DEFAULT NULL,
iEnteredby int DEFAULT NULL,
tEntered datetime DEFAULT NULL,
iUpdatedby int DEFAULT NULL,
tUpdated datetime DEFAULT NULL,
PRIMARY KEY (iRoutingGuideID)
);



CREATE TABLE IF NOT EXISTS grdb_Spreadsheet_map (
iSpreadsheetmapID int NOT NULL AUTO_INCREMENT,
iProgramID int DEFAULT NULL,
cSpreadsheetname varchar(50) DEFAULT NULL,
cCellreference char(2) DEFAULT NULL,
iColumnposition int DEFAULT NULL,
cTablename varchar(50) DEFAULT NULL,
cTablefield varchar(75) DEFAULT NULL,
cTablefieldtext varchar(75) DEFAULT NULL,
cTemperorytablecolumn varchar(75) DEFAULT NULL,
cFieldDescription varchar(75) DEFAULT NULL,
cRecordtype enum('H','D') DEFAULT NULL,
cValidation varchar(250) DEFAULT NULL,
cLabel varchar(100) DEFAULT NULL,
cErrornotification varchar(250) DEFAULT NULL,
cTemplate varchar(50) DEFAULT NULL,
cDefault enum('Y','N') DEFAULT NULL,
cVisible enum('Y','N') DEFAULT NULL,
cVersion varchar(15) DEFAULT NULL,
iStatus int DEFAULT NULL,
iEnteredby int DEFAULT NULL,
tEntered datetime DEFAULT NULL,
iUpdatedby int DEFAULT NULL,
tUpdated datetime DEFAULT NULL,
PRIMARY KEY (iSpreadsheetmapID)
);



CREATE TABLE IF NOT EXISTS grdb_Zerovaluenotes (
iZeronoteID int NOT NULL AUTO_INCREMENT,
iUploadlogID bigint DEFAULT NULL,
iCarrierID int DEFAULT NULL,
cScaccode varchar(20) DEFAULT NULL,
cCustomeralias varchar(20) DEFAULT NULL,
iRegionID int DEFAULT NULL,
cRegioncode varchar(20) DEFAULT NULL,
iCountryID int DEFAULT NULL,
cCountrycode varchar(20) DEFAULT NULL,
iUncodeID int DEFAULT NULL,
cUncode varchar(20) DEFAULT NULL,
cRateType varchar(10) DEFAULT NULL,
iChargecodeID int DEFAULT NULL,
cChargecode varchar(20) DEFAULT NULL,
cNotes text,
iProcesslock enum('Y','N') DEFAULT NULL,
cSelectType enum('SIN','MUL','ALL','BLK') DEFAULT NULL,
iStatus tinyint DEFAULT NULL,
iEnteredby int DEFAULT NULL,
tEntered datetime DEFAULT NULL,
iUpdatedby int DEFAULT NULL,
tUpdated datetime DEFAULT NULL,
PRIMARY KEY (iZeronoteID)
);



CREATE TABLE IF NOT EXISTS grdb_Zerovaluenotes_Customer (
iCustomerID bigint unsigned NOT NULL AUTO_INCREMENT,
iZeronoteID int DEFAULT NULL,
cCustomeralias varchar(20) DEFAULT NULL,
iOption1 int DEFAULT NULL,
iOption2 int DEFAULT NULL,
iOption3 int DEFAULT NULL,
iStatus int DEFAULT NULL,
iEnteredby int DEFAULT NULL,
tEntered datetime DEFAULT NULL,
iUpdatedby int DEFAULT NULL,
tUpdated datetime DEFAULT NULL,
PRIMARY KEY (iCustomerID)
);